export const cont = [
  {
  "titulo" : "Volume I",
  "indice" : [
    {"titulo" : "Apresentação",
     "pagina" : "v1_0_apresentacao",
     "autoria" : ["Danniel da Silva Carvalho", "João Paulo Lazzarini-Cyrino"]
    },
    {"parte" : ""},
    {"titulo" : "Uma Introdução ao Estudo da História",
      "autoria" : ["Ana Carolina Barbosa Pereira"],
      "pagina" : "v1_1_introducao_historia"},
    {"titulo" : "Dez obras para conhecer Estruturalismo",
      "autoria" : ["Danniel da Silva Carvalho", "João Paulo Lazzarini-Cyrino"],
      "pagina" : "v1_2_estruturalismo"},
    {"titulo" : "Dez obras para conhecer Funcionalismo Linguístico",
      "autoria" : ["Emília Helena Portella Monteiro de Sousa", "Cristina dos Santos Carvalho"],
      "pagina" : "v1_3_funcionalismo"},
    {"titulo" : "Dez obras para conhecer Gramática Gerativa",
      "autoria" : ["Danniel da Silva Carvalho","Lílian Teixeira de Sousa"],
      "pagina" : "v1_4_gramatica_gerativa"},
    {"titulo" : "Dez obras para conhecer Sociolinguística",
      "autoria" : ["Gredson dos Santos"],
      "pagina" : "v1_5_sociolinguistica"},
    {"titulo" : "Dez obras para conhecer Biolinguística",
      "autoria" : ["Fernanda de Oliveira Cerqueira"],
      "pagina" : "v1_6_biolinguistica"},    
    {"titulo" : "Dez obras para conhecer Fonética",
      "autoria" : ["Felipe Flores Kupske"],
      "pagina" : "v1_7_fonetica"}, 
    {"titulo" : "Dez obras para conhecer Morfologia",
      "autoria" : ["Antonia Vieira dos Santos"],
      "pagina" : "v1_8_morfologia"},     
	  {"titulo" : "Dez obras para conhecer Morfologia Histórica",
      "autoria" : ["Mailson Lopes"],
      "pagina" : "v1_10_morfologia_historica"}, 
  	{"titulo" : "Dez obras para conhecer Sintaxe Diacrônica",
      "autoria" : ["Carlos Felipe Pinto"],
      "pagina" : "v1_11_sintaxe_diacronica"}, 
    {"titulo" : "Dez obras para conhecer a Pragmática",
      "autoria" : ["Camilla Santero Pontes", "Cecilia Aguirre"],
      "pagina" : "v1_12_pragmatica"},       
	  {"titulo" : "Dez obras para conhecer Linguística Queer/Cuir",
      "autoria" : ["Rodrigo Borba","Elizabeth Sara Lewis"],
      "pagina" : "v1_13_linguistica_queer"},
    {"titulo" : "Dez obras para conhecer a Linguística Aplicada",
      "autoria" : ["Livia Baptista"],
      "pagina" : "v1_14_linguistica_aplicada"},    
    {"titulo" : "Dez obras para conhecer a Análise Crítica do Discurso",
      "autoria" : ["Daniele de Oliveira"],
      "pagina" : "v1_16_analise_critica_discurso"},
    {"titulo" : "Dez obras para conhecer os Estudos da Tradução",
      "autoria" : ["Ana Maria Bicalho", "Monique Pfau"],
      "pagina" : "v1_17_estudos_da_traducao"},
    {"parte" : "fim"}
  ]
  }
]
